name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Deploys when changes are pushed to the 'main' branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps: # Use the Node.js version compatible with your project

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build # Adjust this command if your build process is different

    - name: Deploy to Firebase Hosting
      uses: w9jds/firebase-action@v2.2.1
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
